### PR TITLE
playwright test setup

### PR DESCRIPTION
**Pull request by smartbartdev**

### CODE REVIEW

**Review by peterpolman — APPROVED** [review]
Looking good! I'll merge it and add it to the pipeline. When will you have the last tests ready? Then we can wrap this up💪

**Comment by peterpolman** [comment]
Screenshot 2024-03-25 at 13 20 48

Hi @smartbartdev! The test seems to be timing out during it's run. It appears to be caused by the rate limit which I have increased a bit already to 60 requests per 60 seconds. 

https://github.com/thxprotocol/monorepo/actions/runs/8417882187/job/23047201594

I've found that individual test cases are running a login again when they starte. Is this necessary and could this be made conditional based on the login state of the worker?

**Comment by peterpolman** [comment]
Hmm I guess they need to login again after switching context. I'm disabling the rate limits for staging and see how that goes!

**Comment by smartbartdev** [comment]
We can reuse login states over the tests most probably yes. There are multiple options for this:

https://playwright.dev/docs/auth

**Pull request merged**
